In [1]:
#Q1
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print("Corrected Temperature:", corrected_temperature)

fahrenheit = corrected_temperature * 9/5 + 32
print("Fahrenheit:", fahrenheit)

greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", greater_than_32)

count = np.sum(corrected_temperature > 32)
print("Count:", count)

print("Vectorization performs operations on the entire array at once instead of processing each element separately.")
print("Boolean indexing directly selects values satisfying a condition, making the code faster and simpler than loops.")

Corrected Temperature: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Count: 5
Vectorization performs operations on the entire array at once instead of processing each element separately.
Boolean indexing directly selects values satisfying a condition, making the code faster and simpler than loops.


In [2]:
#Q2
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total_steps = np.sum(steps)
print("Total Steps:", total_steps)

mean_steps = np.mean(steps)
print("Mean Steps:", mean_steps)

maximum = np.max(steps)
minimum = np.min(steps)

print("Maximum:", maximum)
print("Minimum:", minimum)

day_total = np.sum(steps, axis=0)
print("Total Steps Per Day:", day_total)

user_total = np.sum(steps, axis=1)
print("Total Steps Per User:", user_total)

position = np.unravel_index(np.argmax(steps), steps.shape)

print("Position of Maximum:", position)
print("Maximum Steps:", steps[position])

Total Steps: 84200
Mean Steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total Steps Per Day: [26500 27300 30400]
Total Steps Per User: [18300 24500 14400 27000]
Position of Maximum: (np.int64(3), np.int64(2))
Maximum Steps: 9500


In [3]:
#Q3
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

subset = original[1:5]
print("Subset:", subset)

subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

copied = original[1:5].copy()
copied[0] = 500

print("Original after modifying copy:", original)
print("Copied Array:", copied)

matrix = np.arange(1, 13).reshape(3, 4)
print("Matrix:\n", matrix)

print("First Row:", matrix[0])
print("Last Row:", matrix[-1])
print("Second Column:", matrix[:, 1])
print("Rows 1-2 and Columns 2-3:\n", matrix[1:3, 2:4])

flat_array = matrix.flatten()
ravel_array = matrix.ravel()

print("Flatten:", flat_array)
print("Ravel:", ravel_array)

ravel_array[0] = 100

print("Ravel after modification:", ravel_array)
print("Matrix after modifying ravel:\n", matrix)

flat_array[1] = 200

print("Flatten after modification:", flat_array)
print("Matrix after modifying flatten:\n", matrix)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4 5]
Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copy: [  1 999   3   4   5   6]
Copied Array: [500   3   4   5]
Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First Row: [1 2 3 4]
Last Row: [ 9 10 11 12]
Second Column: [ 2  6 10]
Rows 1-2 and Columns 2-3:
 [[ 7  8]
 [11 12]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel after modification: [100   2   3   4   5   6   7   8   9  10  11  12]
Matrix after modifying ravel:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten after modification: [  1 200   3   4   5   6   7   8   9  10  11  12]
Matrix after modifying flatten:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data Type: int64


In [4]:
#Q4
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("Transpose:\n", XT)

print("Transpose converts the features from columns into rows.")

XT_X = X.T @ X
print("X.T @ X:\n", XT_X)

XT_X_inv = np.linalg.inv(XT_X)
print("Inverse:\n", XT_X_inv)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Coefficients:", beta)

print("The coefficients represent the contribution of sleep hours, activity level and stress level to the assistance score.")

new_user = np.array([5, 40, 7])

prediction = new_user @ beta
print("Predicted Assistance Score:", prediction)

Shape of X: (4, 3)
Dimensions of X: 2
Transpose:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
Transpose converts the features from columns into rows.
X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients: [-0.15921454  0.14083853 10.06302242]
The coefficients represent the contribution of sleep hours, activity level and stress level to the assistance score.
Predicted Assistance Score: 75.27862544779117
