In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Original:", arr)
print("Add 2:", arr + 2)
print("Multiply by 3:", arr * 3)
print("Divide by 2:", arr / 2)

Original: [1 2 3 4 5]
Add 2: [3 4 5 6 7]
Multiply by 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
m = values[np.argmax(counts)]
print("x most frequent:", m)
print("Indices:", np.where(x == m)[0])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
m = values[np.argmax(counts)]
print("y most frequent:", m)
print("Indices:", np.where(y == m)[0])

Reversed: [5 4 6 3 2 1]
x most frequent: 1
Indices: [0 5 7 8 9]
y most frequent: 1
Indices: [0 1 2]


In [3]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [4]:
dhruv = np.linspace(10, 100, 25)

print(dhruv)
print("Dimensions:", dhruv.ndim)
print("Shape:", dhruv.shape)
print("Total elements:", dhruv.size)
print("Data type:", dhruv.dtype)
print("Total bytes:", dhruv.nbytes)

transpose = dhruv.reshape(25, 1)
print("Transpose using reshape:")
print(transpose)

print("Using T:")
print(dhruv.T)

print("T does not change a 1D array")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
T does not change a 1D array


In [5]:
ucs420_dhruv = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])

print("Original:")
print(ucs420_dhruv)

print("Mean:", np.mean(ucs420_dhruv))
print("Median:", np.median(ucs420_dhruv))
print("Max:", np.max(ucs420_dhruv))
print("Min:", np.min(ucs420_dhruv))
print("Unique:", np.unique(ucs420_dhruv))

reshaped_ucs420_dhruv = ucs420_dhruv.reshape(4, 3)
print("Reshaped:")
print(reshaped_ucs420_dhruv)

resized_ucs420_dhruv = np.resize(ucs420_dhruv, (2, 3))
print("Resized:")
print(resized_ucs420_dhruv)

Original:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
[[10 20 30]
 [40 50 60]]
